<table width="100%">
<tr>
   <td width=118px align=center>
           <img src="/~walker/ccbyncsa.png" alt="ccbyncsa.png">
     <td>
     <p><font size="-2">
         Copyright &#169; 2011-2014
         <a href="http://www.cs.grinnell.edu/~walker/">
         <font style="color:white">
         <u>by&nbsp;Henry&nbsp;M.&nbsp;Walker.</u>
         </font></a>
         <br>
         Selected materials copyright by Marge Coahran, Samuel A. Rebelsky, John
         David Stone, and Henry Walker and used by permission. 
         <br>
         This page and other materials developed for CSC 161 are under development. 
         <br>
         This and all laboratory exercises for CSC 161 are licensed under
         a <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">
         <font style="color:white">
         <u>Creative Commons Attribution-NonCommercial-Share Alike 4.0
           International License.</u>
         </font></a>
        </font>
       </p>

</tr>

</table>
