<table width="100%">
<tr>
   <td width=118px align=center>
           <img src="/~walker/ccbyncnd.png" alt="ccbyncsa.png">
     <td>
     <p><font size="-2">
         Copyright &#169; 2011-2014
         <a href="http://www.cs.grinnell.edu/~walker/">
         <u>by&nbsp;Henry&nbsp;M.&nbsp;Walker.</u>
         </a>
         <br>
         Selected materials copyright by Marge Coahran, Samuel A. Rebelsky, John
         David Stone, and Henry Walker and used by permission. 
         <br>
         This page, and other materials developed for CSC 161, are under development. 
         <br>
         All readings and reference materials for CSC 161 are licensed under
         a <a href="http://creativecommons.org/licenses/by-nc-nd/4.0/">
         <u>Creative Commons Attribution-NonCommercial-NoDerivatives 4.0
           International License.</u>
         </a>
       </p>

</tr>

</table>
