</div> <!-- labcontent-->

<div class="footer">
<p>
<hr>
<p>

This document is available on the World Wide Web through the course home page at

<BLOCKQUOTE>
<PRE>
http://www.cs.grinnell.edu/~walker/courses/161.sp14/
</PRE>
</BLOCKQUOTE>

<hr>
<table width="100%">
<tr><td>
   <em>created 5 January 2013</em><br>
   <em>revised 9 June 2014</em>
   </td>
   <td align="right">
   <a href="http://validator.w3.org/check/referer"><img border="0" 
      src="/~walker/valid-html401-blue.png" alt="Valid HTML 4.01!" height="31"
      width="88"></a>
   <a href="http://jigsaw.w3.org/css-validator/"><img border="0"
       src="/~walker/vcss-blue.png" 
       alt="Valid CSS!" height="31"
       width="88"></a>
   </td>
</tr>

</table>

<hr>

<table width="100%">
<tr>
   <td width=118px align=center>
           <img src="/~walker/ccbyncsa.png" alt="ccbyncsa.png">
     <td>
     <p><font size="-2">
         Copyright &#169; 2011-2014
         <a href="http://www.cs.grinnell.edu/~walker/">
         <font style="color:white">
         <u>by&nbsp;Henry&nbsp;M.&nbsp;Walker.</u>
         </font></a>
         <br>
         Selected materials copyright by Marge Coahran, Samuel A. Rebelsky, John
         David Stone, and Henry Walker and used by permission. 
         <br>
         This page and other materials developed for CSC 161 are under development. 
         <br>
         This and all laboratory exercises for CSC 161 are licensed under
         a <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">
         <font style="color:white">
         <u>Creative Commons Attribution-NonCommercial-Share Alike 4.0
           International License.</u>
         </font></a>
        </font>
       </p>

</tr>

</table>

</div> <!-- footer -->
</div> <!-- body -->
