<div class="title-header">
<table width="100%">
<tr>
<td class="font-tiny" width="33%" align="left"><a class="font-tiny"
href="/~walker/courses/161.fa12/index.shtml"> CSC 161</a></td>
<td class="font-tiny" width="33%" align="center">Grinnell College</td>
<td class="font-tiny" width="33%" align="right">Fall, 2012</td>
</tr>
<tr>
<td>&nbsp;</td>
</tr>
<tr>
<td colspan="3" class="font-large" align="left">
Imperative Problem Solving and Data Structures</td>
</tr>
<tr>
<td>&nbsp;</td>
</tr>
</table>
</div>
<div id="header-bottom">&nbsp;</div>
