#!/bin/bash
echo ""
echo "------------------------------------------------------------"
echo ""

# compile 3 programs
gcc -o parking-lot-1 parking-lot-1.c
gcc -lm -o parking-lot-min-max-1 parking-lot-min-max-1.c
gcc -lm -o parking-lot-2 parking-lot-2.c
gcc -lm -o parking-lot-3 parking-lot-3.c

echo program parking-lot-1
parking-lot-1 <<!
$1
$2
$3
$4
$5
$6
!

echo ""
echo program parking-lot-min-max-1
parking-lot-min-max-1 <<!
$1
$2
$3
$4
$5
$6
!

echo ""
echo program parking-lot-2
parking-lot-2 <<!
$1
$2
$3
$4
$5
$6
!

echo ""
echo program parking-lot-3
parking-lot-3 <<!
$1
$2
$3
$4
$5
$6
!
